// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJrKniSpP5R04czAz0pTLp2LSsm94WDtY',
    appId: '1:429732760291:web:7cee447711e400d9ab13d6',
    messagingSenderId: '429732760291',
    projectId: 'taskmanager-93208',
    authDomain: 'taskmanager-93208.firebaseapp.com',
    storageBucket: 'taskmanager-93208.firebasestorage.app',
    measurementId: 'G-Q8LCZ53LVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxF6eq_wS_CD2WowfNR-xpyKhYQSPtsGE',
    appId: '1:429732760291:android:941c7e88cb646f7dab13d6',
    messagingSenderId: '429732760291',
    projectId: 'taskmanager-93208',
    storageBucket: 'taskmanager-93208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB7TIHkmFVUkIZd0v0agunp1HIOYm9YNM',
    appId: '1:429732760291:ios:2b97bb536ce9168aab13d6',
    messagingSenderId: '429732760291',
    projectId: 'taskmanager-93208',
    storageBucket: 'taskmanager-93208.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB7TIHkmFVUkIZd0v0agunp1HIOYm9YNM',
    appId: '1:429732760291:ios:2b97bb536ce9168aab13d6',
    messagingSenderId: '429732760291',
    projectId: 'taskmanager-93208',
    storageBucket: 'taskmanager-93208.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJrKniSpP5R04czAz0pTLp2LSsm94WDtY',
    appId: '1:429732760291:web:af5a8dfa792bc36fab13d6',
    messagingSenderId: '429732760291',
    projectId: 'taskmanager-93208',
    authDomain: 'taskmanager-93208.firebaseapp.com',
    storageBucket: 'taskmanager-93208.firebasestorage.app',
    measurementId: 'G-B2QL2R8GRT',
  );
}
